const byId = (id) => /** @type {HTMLElement|null} */ (document.getElementById(id));

export const elements = {
  chart: /** @type {SVGSVGElement|null} */ (byId('chart')),
  tooltip: byId('tooltip'),
  toast: byId('toast'),
  addWordsInput: /** @type {HTMLInputElement|null} */ (byId('addWords')),
  addButton: /** @type {HTMLButtonElement|null} */ (byId('addBtn')),
  undoButton: /** @type {HTMLButtonElement|null} */ (byId('undoBtn')),
  warpToggle: /** @type {HTMLInputElement|null} */ (byId('warpToggle')),
  warpDate: /** @type {HTMLInputElement|null} */ (byId('warpDate')),
  totalEl: byId('total'),
  pctEl: byId('pct'),
  barEl: /** @type {HTMLElement|null} */ (byId('bar')),
  remainingEl: byId('remaining'),
  todayWordsEl: byId('todayWords'),
  idealEl: byId('ideal'),
  neededEl: byId('needed'),
  projectTitle: byId('projectTitle'),
  motivationBanner: byId('motivationBanner'),
  viewBadge: /** @type {HTMLElement|null} */ (byId('viewBadge')),
  editProjectBtn: /** @type {HTMLButtonElement|null} */ (byId('editProjectBtn')),
  moreBtn: /** @type {HTMLButtonElement|null} */ (byId('moreBtn')),
  actionsMenu: byId('actionsMenu'),
  exportBtn: /** @type {HTMLButtonElement|null} */ (byId('exportBtn')),
  importBtn: /** @type {HTMLButtonElement|null} */ (byId('importBtn')),
  importInput: /** @type {HTMLInputElement|null} */ (byId('importInput')),
  openSettings: /** @type {HTMLButtonElement|null} */ (byId('openSettings')),
  saveSettings: /** @type {HTMLButtonElement|null} */ (byId('saveSettings')),
  closeSettings: /** @type {HTMLButtonElement|null} */ (byId('closeSettings')),
  closeSettings2: /** @type {HTMLButtonElement|null} */ (byId('closeSettings2')),
  resetAllBtn: /** @type {HTMLButtonElement|null} */ (byId('resetAllBtn')),
  settingsPanel: byId('settings'),
  refreshBtn: /** @type {HTMLButtonElement|null} */ (byId('refreshBtn')),
  syncStatus: byId('syncStatus'),
  drawerSyncStatus: byId('drawerSyncStatus'),
  nameInput: /** @type {HTMLInputElement|null} */ (byId('name')),
  goalInput: /** @type {HTMLInputElement|null} */ (byId('goal')),
  startInput: /** @type {HTMLInputElement|null} */ (byId('start')),
  endInput: /** @type {HTMLInputElement|null} */ (byId('end')),
  startingWordsInput: /** @type {HTMLInputElement|null} */ (byId('startingWords')),
  themeSelect: /** @type {HTMLSelectElement|null} */ (byId('themeSelect')),
  drawer: byId('drawer'),
  entriesContainer: byId('entries'),
  editEntriesBtn: /** @type {HTMLButtonElement|null} */ (byId('editEntriesBtn')),
  closeEntries: /** @type {HTMLButtonElement|null} */ (byId('closeEntries')),
  closeEntries2: /** @type {HTMLButtonElement|null} */ (byId('closeEntries2')),
  jumpDate: /** @type {HTMLSelectElement|null} */ (byId('jumpDate')),
  authBtn: /** @type {HTMLButtonElement|null} */ (byId('authBtn')),
  authBar: byId('authbar'),
  authBarBtn: /** @type {HTMLButtonElement|null} */ (byId('authBarBtn')),
  loginPanel: byId('login'),
  closeLogin: /** @type {HTMLButtonElement|null} */ (byId('closeLogin')),
  loginTitle: byId('loginTitle'),
  emailInput: /** @type {HTMLInputElement|null} */ (byId('email')),
  sendLinkBtn: /** @type {HTMLButtonElement|null} */ (byId('sendLink')),
  signOutBtn: /** @type {HTMLButtonElement|null} */ (byId('signOut')),
  signInPane: byId('signInPane'),
  signedInPane: byId('signedInPane'),
  loginStatus: byId('loginStatus'),
  resendLinkBtn: /** @type {HTMLButtonElement|null} */ (byId('resendLink')),
  accountChip: /** @type {HTMLElement|null} */ (byId('accountChip')),
  accountEmail: byId('accountEmail'),
  acctEmail2: byId('acctEmail'),
  warpPopover: byId('warpPopover'),
  currentDateInfo: byId('currentDateInfo'),
};

export function requireElement(element, name) {
  if (!element) throw new Error(`Missing DOM element: ${name}`);
  return element;
}
